"""Auto-generated by setuptools_scm during packaging.

This placeholder keeps imports working in editable installs before the first
tag-derived version is written. Do not edit manually; it will be overwritten.
"""

version = "2.0.1"

